language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: COMPOSER_FLAG=--prefer-lowest

before_script:
  # Composer
  - travis_retry composer install --no-interaction
  # Coverage
  - if [[ "$TRAVIS_PHP_VERSION" == "7.4" && "$COMPOSER_FLAG" == "" ]]; then COVERAGE=1; fi

script:
  # Quality Assurance
  - composer run-script qa-linter
  - composer run-script qa-codesniffer

  # Nette\Tester
  - composer run-script qa-tester-info
  - composer run-script qa-tester

  # Nette\Tester + CodeCoverage
  - if [ "$COVERAGE" != "" ]; then composer run-script qa-tester-coverage-info; fi
  - if [ "$COVERAGE" != "" ]; then composer run-script qa-tester-coverage; fi

after_script:
  # Coverage (Coveralls)
  - if [ "$COVERAGE" != "" ]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi
  - if [ "$COVERAGE" != "" ]; then php coveralls.phar --verbose --config tests/.coveralls.yml; fi

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
